baseURL: https://londonaesperantoklubo.com/
defaultContentLanguage: eo
title: LEK
disableKinds: [ "taxonomy", "sitemap" ]
# sectionPagesMenu: "smain"
outputs:
  home:
  - html
  page:
  - html
  section:
  - html

markup:
  goldmark:
    renderer:
      unsafe: true