baseURL: https://undeconstructed.github.io/lek-retejo/
defaultContentLanguage: eo
title: LEK
disableKinds: [ "taxonomy", "taxonomyTerm", "sitemap" ]
# sectionPagesMenu: "smain"
outputs:
  home:
  - html
  page:
  - html
  section:
  - html
