#!/bin/bash

read -e -p "Nomo: " nomo
if test -z "$nomo"; then exit 1; fi

etikedo0=$(echo ${nomo} | tr -s " [:upper:]ĈĜĤĴŜŬ" "-[:lower:]ĉĝĥĵŝŭ" | tr -dc "[:alnum:]ĉĝĥĵŝŭ-")
read -e -p "Etikedo: " -i "${etikedo0}" etikedo
if test -z "$etikedo"; then exit 1; fi

read -e -p "Loko: " -i "Highbury" loko
if test -z "$loko"; then exit 1; fi

dato0=$(date -I)
read -e -p "Dato (YYYY-MM-DD): " -i ${dato0} dato
if test -z "$dato"; then exit 1; fi

read -e -p "Horo (HH:MM): " -i "19:00" horo
if test -z "$horo"; then exit 1; fi

read -e -p "Eventa Servo: " eventaservo

dosiero="content/eventoj/${dato}-${etikedo}.md"

cat << xxx > ${dosiero}
---
title: '${nomo}'
eventdato: ${dato}T${horo}:00+00:00
eventaservo: ${eventaservo}
loko: ${loko}
menu:
  main:
    parent: "Eventoj"
---


xxx

vi "+normal G$" +startinsert ${dosiero}

echo "Kreis " $dosiero
